# Generated by Django 4.2.7 on 2023-11-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numhabitacion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('max_personas', models.IntegerField()),
                ('edificio', models.CharField(max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.categoriahab')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField()),
                ('fechaSalida', models.DateField()),
                ('num_personas', models.IntegerField()),
                ('nom_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.cliente')),
                ('numhabitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.habitaciones')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.tipopago')),
            ],
        ),
    ]
